// Catalogue VIGIE des zones maritimes à risque.
// Chaque zone : géométrie (centre + rayon km), type, risque structurel de base (0-3),
// drapeau JWC (zone listée par le Joint War Committee des assureurs de Londres),
// mots-clés GDELT (presse mondiale, anglais) et contexte historique (français).
// Révision éditoriale : juillet 2026. À revoir à chaque bulletin JWLA.

export const ZONES = [
  // ================= Mer Rouge & océan Indien ouest =================
  { id:'bab-el-mandeb', name:'Bab el-Mandeb', c:[12.6,43.4], r:300, type:'détroit', base:2.5, jwc:true,
    query:'"Bab el-Mandeb" OR "Bab al-Mandab" OR "Houthi"',
    ctx:'Verrou sud de la mer Rouge (30 km de large), passage obligé Europe–Asie. Depuis fin 2023, cible régulière d’attaques houthies (missiles, drones navals) qui ont provoqué le plus grand déroutement du commerce maritime depuis des décennies.' },
  { id:'redsea-n', name:'Mer Rouge nord', c:[24,36.5], r:500, type:'conflit', base:1.5, jwc:true,
    query:'"Red Sea"',
    ctx:'Corridor d’approche du canal de Suez. Exposée par contagion aux tensions du sud de la mer Rouge ; mines et embarcations piégées y ont été signalées par le passé.' },
  { id:'suez', name:'Canal de Suez', c:[30.8,32.35], r:200, type:'détroit', base:1.5, jwc:false,
    query:'"Suez Canal"',
    ctx:'12 % du commerce mondial. Point de fragilité logistique extrême : l’échouement de l’Ever Given (2021) a coûté ~10 Md$/jour au commerce mondial. Les revenus du canal chutent fortement à chaque crise en mer Rouge.' },
  { id:'aden', name:'Golfe d’Aden', c:[12.8,48.5], r:450, type:'mixte', base:2, jwc:true,
    query:'"Gulf of Aden"',
    ctx:'Zone de transit sous escorte internationale (opérations Atalanta, Prosperity Guardian). Cumul historique piraterie somalienne + attaques houthies côté yéménite.' },
  { id:'somalia', name:'Bassin somalien', c:[4,51], r:700, type:'piraterie', base:1.5, jwc:true,
    query:'"Somalia"',
    ctx:'Épicentre mondial de la piraterie 2008-2012 (plus de 200 attaques/an au pic). Fortement réduite par les patrouilles internationales, avec des résurgences opportunistes lors des relâchements de vigilance.' },
  { id:'mozambique', name:'Canal du Mozambique', c:[-12.5,41.5], r:500, type:'conflit', base:1, jwc:false,
    query:'"Cabo Delgado" OR "Mozambique Channel"',
    ctx:'Route alternative du Cap et bassin gazier majeur (projets GNL). Insurrection jihadiste au Cabo Delgado depuis 2017, avec incursions côtières épisodiques.' },

  // ================= Golfe Persique & alentours =================
  { id:'hormuz', name:'Détroit d’Ormuz', c:[26.4,56.4], r:300, type:'détroit', base:2, jwc:true,
    query:'"Strait of Hormuz" OR "Hormuz"',
    ctx:'Un cinquième du pétrole mondial dans un goulet de 40 km. Saisies de navires par les Gardiens de la révolution, brouillage GPS récurrent, menace de fermeture brandie à chaque escalade avec l’Iran.' },
  { id:'persian-gulf', name:'Golfe Persique', c:[27,51.5], r:500, type:'conflit', base:1.5, jwc:true,
    query:'"Persian Gulf" OR "Arabian Gulf"',
    ctx:'Concentration mondiale d’infrastructures pétrolières et de bases militaires. Théâtre direct de toute confrontation Iran / États du Golfe / marines occidentales.' },
  { id:'oman-gulf', name:'Golfe d’Oman', c:[24.8,58.5], r:350, type:'mixte', base:1.5, jwc:true,
    query:'"Gulf of Oman"',
    ctx:'Antichambre d’Ormuz. Attaques de tankers en 2019 (mines-ventouses), saisies et abordages par drones : premier signal des escalades avec l’Iran.' },

  // ================= Mer Noire & Méditerranée =================
  { id:'blacksea-nw', name:'Mer Noire nord-ouest', c:[45.3,30.8], r:400, type:'conflit', base:2.5, jwc:true,
    query:'"Odesa" OR "Odessa" OR "Black Sea"',
    ctx:'Guerre Russie–Ukraine : corridor céréalier ukrainien sous menace permanente, frappes sur les ports d’Odesa, mines dérivantes. Zone d’exclusion assurantielle majeure.' },
  { id:'azov-kerch', name:'Mer d’Azov · Kerch', c:[45.9,36.4], r:300, type:'conflit', base:2.5, jwc:true,
    query:'"Kerch" OR "Sea of Azov"',
    ctx:'Mer fermée contrôlée par la Russie depuis 2022, pont de Kerch régulièrement ciblé. Navigation commerciale internationale quasi inexistante.' },
  { id:'bosphorus', name:'Bosphore · Dardanelles', c:[40.6,28.2], r:250, type:'détroit', base:1.5, jwc:false,
    query:'"Bosphorus" OR "Bosporus" OR "Dardanelles"',
    ctx:'Seule sortie de la mer Noire, régie par la convention de Montreux (la Turquie peut fermer aux navires de guerre). Trafic dense, incidents de navigation fréquents, enjeu direct de la guerre en Ukraine.' },
  { id:'levant', name:'Méditerranée orientale', c:[33.8,34.5], r:400, type:'conflit', base:1.5, jwc:true,
    query:'"Eastern Mediterranean" OR "Gaza" OR "Lebanon"',
    ctx:'Façade maritime des conflits du Levant (Gaza, Liban, Syrie). Ports frappés ou bloqués par phases, gisements gaziers offshore disputés, forte présence navale internationale.' },
  { id:'libya', name:'Côte libyenne', c:[32.8,15], r:450, type:'conflit', base:1.5, jwc:true,
    query:'"Libya"',
    ctx:'Pays fracturé entre gouvernements rivaux ; terminaux pétroliers régulièrement bloqués au gré des rapports de force. Zone d’opérations migratoires et navales denses.' },
  { id:'gibraltar', name:'Détroit de Gibraltar', c:[35.95,-5.6], r:200, type:'détroit', base:1, jwc:false,
    query:'"Strait of Gibraltar" OR "Gibraltar"',
    ctx:'Porte Atlantique–Méditerranée (~300 navires/jour). Risque surtout opérationnel (densité, orques attaquant les safrans depuis 2020) ; épisodes de tensions autour des eaux de Gibraltar.' },

  // ================= Asie-Pacifique =================
  { id:'taiwan', name:'Détroit de Taïwan', c:[24.2,119.6], r:350, type:'détroit', base:2, jwc:false,
    query:'"Taiwan Strait" OR "Taiwan"',
    ctx:'Point de friction majeur Chine–Taïwan–États-Unis. Exercices militaires d’encerclement récurrents ; un blocus paralyserait ~50 % de la flotte mondiale de porte-conteneurs qui croise à proximité.' },
  { id:'scs', name:'Mer de Chine méridionale', c:[11,114], r:800, type:'conflit', base:1.5, jwc:false,
    query:'"South China Sea" OR "Spratly" OR "Scarborough Shoal"',
    ctx:'Revendications chinoises contestées (ligne en neuf traits), îlots militarisés, incidents répétés entre garde-côtes chinois et navires philippins ou vietnamiens. Un tiers du commerce mondial y transite.' },
  { id:'ecs', name:'Mer de Chine orientale', c:[26.5,124], r:450, type:'conflit', base:1, jwc:false,
    query:'"East China Sea" OR "Senkaku" OR "Diaoyu"',
    ctx:'Contentieux sino-japonais autour des Senkaku/Diaoyu ; incursions quasi quotidiennes de garde-côtes chinois. Corridor d’accès aux grands ports chinois, japonais et coréens.' },
  { id:'korea', name:'Mer Jaune · Corée', c:[37.5,124.5], r:400, type:'conflit', base:1, jwc:false,
    query:'"North Korea" OR "Yellow Sea"',
    ctx:'Tirs de missiles nord-coréens au-dessus des routes maritimes, frontière maritime contestée (ligne de limite nord), incidents navals intercoréens historiques.' },
  { id:'malacca', name:'Malacca · Singapour', c:[2.8,100.8], r:400, type:'détroit', base:1.5, jwc:false,
    query:'"Malacca" OR "Singapore Strait"',
    ctx:'Passage le plus fréquenté du monde (~90 000 navires/an). Vols à main armée opportunistes sur navires au mouillage, risque de collision élevé ; suivi ReCAAP permanent.' },
  { id:'sulu', name:'Mers de Sulu · Célèbes', c:[6,120.5], r:500, type:'piraterie', base:1.5, jwc:false,
    query:'"Sulu Sea" OR "Abu Sayyaf" OR "Celebes Sea"',
    ctx:'Historique d’enlèvements d’équipages par Abu Sayyaf (2016-2020), fortement réduit par les patrouilles trilatérales Indonésie–Malaisie–Philippines. Vigilance maintenue.' },
  { id:'sunda', name:'Détroit de la Sonde', c:[-6,105.5], r:200, type:'détroit', base:1, jwc:false,
    query:'"Sunda Strait" OR "Krakatau" OR "Krakatoa"',
    ctx:'Alternative à Malacca entre Java et Sumatra. Risque avant tout naturel : volcan Anak Krakatau actif (tsunami meurtrier en 2018), forte sismicité.' },
  { id:'lombok', name:'Lombok · Makassar', c:[-7,116.5], r:350, type:'détroit', base:0.5, jwc:false,
    query:'"Lombok Strait" OR "Makassar Strait"',
    ctx:'Route de contournement en eaux profondes pour les plus gros navires. Faible risque politique ; sismicité et trafic croissant.' },
  { id:'luzon', name:'Détroit de Luzon', c:[20.8,121], r:300, type:'détroit', base:1, jwc:false,
    query:'"Luzon Strait" OR "Bashi Channel"',
    ctx:'Porte du Pacifique entre Taïwan et les Philippines, sur-fréquentée par les marines militaires ; couloir de typhons une bonne partie de l’année.' },
  { id:'bengal', name:'Golfe du Bengale', c:[16.5,92.5], r:500, type:'mixte', base:1, jwc:false,
    query:'"Bay of Bengal" OR "Myanmar" OR "Rakhine"',
    ctx:'Cyclones parmi les plus meurtriers du monde ; guerre civile birmane débordant sur la façade maritime (Rakhine), trafics et flux de réfugiés rohingyas.' },

  // ================= Europe du Nord & Arctique =================
  { id:'dover', name:'Manche · Pas de Calais', c:[50.5,0.5], r:300, type:'détroit', base:1, jwc:false,
    query:'"English Channel" OR "Strait of Dover"',
    ctx:'Détroit le plus fréquenté du monde avec Malacca. Risque essentiellement opérationnel : densité extrême, météo, traversées migratoires créant des situations SAR quotidiennes.' },
  { id:'baltic', name:'Mer Baltique', c:[58.5,20], r:600, type:'conflit', base:1.5, jwc:false,
    query:'"Baltic Sea" OR "shadow fleet" OR "undersea cable"',
    ctx:'Nouvelle ligne de front hybride : sabotages de câbles et gazoducs sous-marins, « flotte fantôme » russe sous sanctions, brouillage GNSS massif signalé par les équipages depuis 2023.' },
  { id:'danish', name:'Détroits danois', c:[55.5,11.5], r:250, type:'détroit', base:1, jwc:false,
    query:'"Oresund" OR "Great Belt" OR "Danish straits"',
    ctx:'Verrou d’entrée-sortie de la Baltique, transit du pétrole russe sous sanctions (inspections renforcées, navires de la flotte fantôme non assurés).' },
  { id:'barents', name:'Mer de Barents', c:[70.5,35], r:500, type:'conflit', base:1, jwc:false,
    query:'"Barents Sea" OR "Northern Fleet" OR "Murmansk"',
    ctx:'Bastion de la Flotte du Nord russe (sous-marins nucléaires). Militarisation croissante de l’Arctique et ouverture progressive de la route maritime du Nord.' },

  // ================= Afrique de l'Ouest =================
  { id:'gog', name:'Golfe de Guinée', c:[3.2,3.5], r:550, type:'piraterie', base:2, jwc:true,
    query:'"Gulf of Guinea"',
    ctx:'Longtemps zone la plus dangereuse du monde pour les équipages (enlèvements contre rançon). Net recul depuis 2021 grâce aux patrouilles régionales, mais capacité criminelle intacte au large du Nigeria.' },
  { id:'niger-delta', name:'Delta du Niger', c:[4.3,6.5], r:250, type:'piraterie', base:2, jwc:true,
    query:'"Niger Delta"',
    ctx:'Cœur pétrolier nigérian : sabotages d’oléoducs, vol de brut à échelle industrielle, groupes armés fluviaux. Source historique de la piraterie du golfe de Guinée.' },

  // ================= Amériques =================
  { id:'panama', name:'Canal de Panama', c:[9.1,-79.6], r:250, type:'détroit', base:1, jwc:false,
    query:'"Panama Canal"',
    ctx:'5 % du commerce mondial. Vulnérabilité climatique structurelle : les sécheresses réduisent les transits (files d’attente, enchères de créneaux). Regain de tensions politiques autour de son statut.' },
  { id:'venezuela', name:'Caraïbes sud · Venezuela', c:[11.5,-65], r:500, type:'conflit', base:1.5, jwc:false,
    query:'"Venezuela" OR "Essequibo" OR "Guyana"',
    ctx:'Contentieux Venezuela–Guyana sur l’Essequibo (pétrole offshore), sanctions sur le brut vénézuélien, opérations navales américaines anti-narcotiques : cocktail volatil.' },
  { id:'haiti', name:'Haïti · passage du Vent', c:[19,-73], r:300, type:'conflit', base:1.5, jwc:false,
    query:'"Haiti" OR "Port-au-Prince"',
    ctx:'Effondrement sécuritaire : gangs contrôlant le port de Port-au-Prince, pillages de navires à quai, approvisionnement du pays sous escorte.' },
  { id:'guayaquil', name:'Golfe de Guayaquil', c:[-2.8,-80.8], r:250, type:'piraterie', base:1, jwc:false,
    query:'"Guayaquil" OR "Ecuador"',
    ctx:'Premier port bananier mondial devenu plaque tournante de la cocaïne vers l’Europe : contaminations de conteneurs, violences portuaires, abordages de navires au mouillage.' },

  // ================= Routes de contournement =================
  { id:'capegoodhope', name:'Cap de Bonne-Espérance', c:[-35.2,19], r:350, type:'détroit', base:0.5, jwc:false,
    query:'"Cape of Good Hope" OR "Cape Town"',
    ctx:'Route de déroutement quand Suez/mer Rouge se ferment (+10 à 14 jours). Mer parmi les plus dures du monde (vagues scélérates) ; surcharge portuaire sud-africaine chronique.' },
];

export default ZONES;
